version: "3.7"

services:


  php8.5-cli:
    image: php:8.5.0RC3-cli-alpine3.21
    container_name: php-video
    tty: true
    build:
      dockerfile: ./Dockerfile
    ports:
      - "3478:3478"
    volumes:
      - ./.:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

